create table if not exists public.portfolio_visits (
  id bigint generated by default as identity primary key,
  visited_on date not null default current_date,
  created_at timestamptz not null default now()
);

alter table public.portfolio_visits enable row level security;

drop policy if exists "Allow anonymous visit tracking" on public.portfolio_visits;

create policy "Allow anonymous visit tracking"
on public.portfolio_visits
for insert
to anon, authenticated
with check (true);

create or replace function public.get_portfolio_traffic()
returns table (date date, visits bigint)
language sql
security definer
set search_path = public
as $$
  select visited_on as date, count(*) as visits
  from public.portfolio_visits
  group by visited_on
  order by visited_on;
$$;

grant execute on function public.get_portfolio_traffic() to anon, authenticated;

create table if not exists public.portfolio_content (
  id text primary key,
  content jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.portfolio_content enable row level security;

drop policy if exists "Allow public portfolio content reads" on public.portfolio_content;
create policy "Allow public portfolio content reads"
on public.portfolio_content
for select
to anon, authenticated
using (true);

drop policy if exists "Allow admin portfolio content writes" on public.portfolio_content;
create policy "Allow admin portfolio content writes"
on public.portfolio_content
for insert
to anon, authenticated
with check (true);

drop policy if exists "Allow admin portfolio content updates" on public.portfolio_content;
create policy "Allow admin portfolio content updates"
on public.portfolio_content
for update
to anon, authenticated
using (true)
with check (true);
